### ISSUE TITLE
Asyncomplete support

### ISSUE THREAD

**Issue by squareduck** [codota/tabnine-vim#10]
Hi, thanks for this awesome completion plugin!
I enjoy using it and it's very helpful, but unfortunately it does not fit into my workflow.
I use asyncomplete, because its fast and provides lots of features (such as lsp completion support).

Please consider implementing Asyncomplete-compatible vim plugin:
https://github.com/prabirshrestha/asyncomplete.vim#using-existing-vim-plugin-sources

I would probably do it myself, but redistributing your binaries and keeping them up to date feels a bit wrong to do from outside.

**Comment by zxqfl** [comment]
Hi @squareduck, since you expressed potential interest in writing a client, you could take a look at the [guide](https://github.com/zxqfl/TabNine/blob/master/HowToWriteAClient.md). (The binary manages its own updates so you don't need to keep it up to date yourself.)

I will keep your suggestion in mind and consider implementing asyncomplete support in the future.

**Comment by prabirshrestha** [comment]
Haven't tried it but you can find it at https://github.com/kitagry/asyncomplete-tabnine.vim

I have updated README.md in asyncomplete.vim.
