### ISSUE TITLE
Stale warnings

### ISSUE THREAD

**Issue by nathasm** [codota/tabnine-vim#13]
When editing a React JSX file (with `flow lsp` enabled) and experience a flow warning about missing return type, unknown types, or something similar. I remove or fix that section of code, and yet I still get errors like:

    InferError: Missing type annotation for `XXXXX`

or

    Cannot resolve name `XXXXX`

e.g.

First

```
import React, { Component } from 'react';

export default class Container extends Component<TestProps> {
}
```

You should get an error stating

    Cannot resolve name `TestProps`

So then modify the file as such

```
import React, { Component } from 'react';

type TestProps = {}

export default class Container extends Component<TestProps> {
}
```

The only way that I have been able to resolve the issue is by closing and reopening the file.

**Comment by zxqfl** [comment]
Hi, I wasn't able to reproduce the issue. Probably the issue is caused because you have configuration intended for YCM but which is being picked up by TabNine (since it is a fork of YCM and still contains most of the code).

In the future I plan to clean up the codebase and remove the code that isn't used by TabNine. This will hopefully fix this issue.

**Comment by nathasm** [comment]
Interesting, I have never used YCM so I have no prior settings/configuration associated with that plugin. I'll have to do some digging and see if I can isolate my issue

**Comment by zxqfl** [comment]
I might have been unable to reproduce because I don't have your `.flowconfig`. If you post it I can try to reproduce the issue again.
