### ISSUE TITLE
Provide keyboard shortcut to close tabnine auto complete window

### ISSUE THREAD

**Issue by dannyalan** [codota/tabnine-vim#20]
Issue originally and incorrectly opened against https://github.com/zxqfl/TabNine/issues/59 

Firstly, cracking plugin! I use this in vim and it has transformed the way in which I develop! Nice one!

This issue is to recognise the lack of a keyboard shortcut (I use Vim 8) to close the auto complete window. In Visual Studio products, the shortcut is (esc) although, this takes me out of Insert mode and even at that, the auto complete window still does not close until I press any other key.

The ability to close or hide the auto complete window would allow me entire visibility of the code I am editing again so I can gently stroke my beard and think carefully of my next bold code change!

**Comment by soonseah** [comment]
agreed. in vim, i am using snipmate and was trying to close the autocomplete window for tabnine, so that i can fire the snipmate snippets (template code) when i needed to....but now, i can't do that (unless i hit 'ESC' and 'a' keys to exit and re-enter insert mode, which makes the autocomplete window goes away, but the defaults the purpose as it is too many keystrokes to have the benefits)

**Comment by Shougo** [comment]
You can close the window by C-e key.
