### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by horseinthesky** [codota/tabnine-vim#34]
I couldn't find any docs regarding how to get started.

I've installed this plugin via:
```
Plug 'zxqfl/tabnine-vim'
```
and it is doing absolutely nothing.

How to enable all these great completions from ads videos?

**Comment by rebuilt** [comment]
Same.  I have also been unsuccessful in getting it to run.  I've tried installing with Vundle and without.  When I try to call TabNine::version in vim I get the error: "Not an editor command: TabNine::version"

**Comment by Shougo** [comment]
TabNine::version is not command.
You need to write it in the buffer.

**Comment by jaydorsey** [comment]
I'm also using vim-plug. I did notice that I needed to run the command `:PlugInstall` and wait a bit for it to finish installing (maybe there's an after-hook that downloads tabnine?)

After that, it seemed to work without any other settings/setup/configuration

@rebuilt You need to write it in a buffer somewhere as shougo noted, it's not a command.

Correct way, just as regular text on a buffer:

![image](https://user-images.githubusercontent.com/191564/64532713-0af75780-d2e0-11e9-850d-6f89ce2dd4e6.png)

It is kind of a weird way to run it, because you just delete that line after you see it print it's info

**Comment by ahmadshiddiq** [comment]
So after `PlugInstall` just wait for the download in the background?
