### ISSUE TITLE
Upstream improvements?

### ISSUE THREAD

**Issue by xloem** [codota/tabnine-vim#91]
I'm noting that this wonderful free project is a fork of a core upstream free project.  Presumably forked to access a non-free service.

For those of us interested in using and contributing to free software, have there been any plans to normalise the work done here into part of the upstream projects?

gz#5836

**Comment by bilucodota** [comment]
Hi @xloem thanks for reaching out
As you know.. we're working these days to (hopefully) deprecate this project and integrate into YCM naturally 
See: https://github.com/ycm-core/ycmd/pull/1588

**Comment by xloem** [comment]
Like many people I am working on a similar project myself.  I would love to integrate my work better with the work of others, so we can all build with each other more effectively.

I was surprised in your PR that you added a user-accessible option rather than a new backend, and I get feeling frightened, worried that free software might not be included in everyone's future work.  But I'm hopeful that we can at least improve backends like ycmd to provide for new features, such as function body prediction.

Are there further plans on your end?

**Comment by bilucodota** [comment]
Reason for the PR being a configuration rather than a new backend - cause it's less invasive, plus ycmd benefits from the option to register new completion providers, an API which is pretty standard nowadays.

The backend itself is [open sourced ](https://github.com/tabnine/ycmd), however it does nothing much rather than communicating with Tabnine binary. 

The binary itself is closed source as of today - but note that Tabnine offers (and always will!) a free version.

**Comment by xloem** [comment]
Thanks for your replies.

By free I meant as in freedom rather than beer, as in e.g. https://www.youtube.com/watch?v=Ag1AKIl_2GM .

It's really wonderful of Tabnine to give normal coders access to some of the advanced technology going around.  I'm sure we'll all be working to increase the access.
